# Generated by Django 6.0.6 on 2026-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file_name', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
                ('job_description', models.TextField()),
                ('score', models.IntegerField()),
                ('matched_keywords', models.JSONField()),
                ('missing_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
